apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: CreditRatingDataJob
spec:
  schedule: "0/5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: creditriskdatajob
            image: arunramakani/creditriskdatajob
	    args:
       	    - "--ignore-db-dir"
            - "lost+found"
          restartPolicy: OnFailure
          volumeMounts:
          - name: credit-rating-storage
            mountPath: /creditrating
        volumes:
        - name: credit-rating-storage
          persistentVolumeClaim:
            claimName: credit-rating-pvc
